### ISSUE TITLE
Need to enable HTTPS for Insilico for Stripe

### ISSUE THREAD

**Issue by FloodThinkingUSD** [marandino/insilico#10]
Need to enable HTTPS for Insilico for Stripe integration. Some users are reporting issues with loading the stripe payment portal.

**Comment by FloodThinkingUSD** [comment]
Also site is not secure for some people, not sure how to fix that

**Comment by marandino** [comment]
Are you sharing the https:// link? if you share just http://insilicotrading.info that'll result in a "non secure site"

**Comment by marandino** [comment]
I can't replicate the issue on my terminal, please let me know:

**To Reproduce**
Steps to reproduce the behavior:
1. The exact link the user is clicking
2. User e-mail
3. The package he/she's attempting to buy

**if on Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]

**if Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]

@FloodThinkingUSD

**Comment by marandino** [comment]
> Are you sharing the https:// link? if you share just http://insilicotrading.info that'll result in a "non secure site"

Even accessing the site this way is not triggering a non SSL alert, just tested on Chrome and Edge.

![image](https://user-images.githubusercontent.com/16166216/89845730-30878380-db77-11ea-855d-aa5831292b01.png)

**Comment by FloodThinkingUSD** [comment]
Can you force https redirect? People can still access the http version

**Comment by marandino** [comment]
I've added a middleware to redirect any person getting into http:// so it sends them back to https://

This is a blind fix as I was unable to replicate the issue, so lmk if it does persist

**Comment by FloodThinkingUSD** [comment]
Ya and https://www.insilicotrading.info/ works, but https://insilicotrading.info/ doesn't

**Comment by FloodThinkingUSD** [comment]
Thanks !

**Comment by marandino** [comment]
Will get to work on it, couple minutes more. 

I'm apologise the whole password reset took me so long, I messed it up when adding the email templates.

**Comment by FloodThinkingUSD** [comment]
No problem man

**Comment by marandino** [comment]
Should be working already.

It's currently working on: 

- [x] Windows | Chrome
- [x] Windows | Edge
- [x] Android | Chrome
- [x] Linux | Chrome

**Comment by FloodThinkingUSD** [comment]
when you just type in insilicotrading.info it is a non https website. Any way to redirect this?

**Comment by marandino** [comment]
Right, it stopped working when I added the non "www" redirection. Give me some more time so I can get both working at the same time
