### ISSUE TITLE
Contact form error

### ISSUE THREAD

**Issue by FloodThinkingUSD** [marandino/insilico#11]
When people try to fill out contact form they are getting an error message and our gsuite email is being spammed.

**Comment by marandino** [comment]
working on it

**Comment by FloodThinkingUSD** [comment]
Thanks!

**Comment by FloodThinkingUSD** [comment]
Getting more reports contact form is broken. Just fyi

**Comment by FloodThinkingUSD** [comment]
Somebody is just filling out an empty contract form and it's spamming our inbox.

**Comment by marandino** [comment]
Can't find the issue yet, it's working properly on development. Was it working yesterday? before we changed the HTTPS?

**Comment by FloodThinkingUSD** [comment]
It's because someone is spamming the form with an empty contact form.

**Comment by FloodThinkingUSD** [comment]
working now

**Comment by marandino** [comment]
This will take me a bit longer, I've deactivated the contact form so this spammer will have to use the e-mail route.

**Comment by marandino** [comment]
Wait, what? was it working?

**Comment by marandino** [comment]
Your guys are talented, I'll have to use one of those annoying captchas, I wanted to avoid it but well...

**Comment by marandino** [comment]
should be working now.
