### ISSUE TITLE
Website update

### ISSUE THREAD

**Issue by FloodThinkingUSD** [marandino/insilico#12]
Hello, 
We are going to have another dev take a look at the website and make some changes, can we please get this stuff ASAP.

1. .env files from the previous dev containing all keys IMPORTANT
2. credentials to heroku account, if it is not the developers personal account 
3. access to the account used to set up the database, or an export of the current database IMPORTANT

**Comment by marandino** [comment]
Hi, 

Please send me this dev's e-mail, as I won't be publishing the dev keys on github. 
I can grant heroku access to his e-mail as well if provided.
And yeah, I already made a Mongo Atlas user for him.

**Comment by marandino** [comment]
Anyways, I'd suggest him pushing the changes to github, rather than directly pushing onto Heroku, as it'll be easier for us both to be at the same page.

**Comment by FloodThinkingUSD** [comment]
Can you send it here please!

ventuxpro@Outlook.com

**Comment by FloodThinkingUSD** [comment]
can you send the whole .env file

**Comment by marandino** [comment]
done
