### ISSUE TITLE
Remove Domain Please

### ISSUE THREAD

**Issue by FloodThinkingUSD** [marandino/insilico#13]
I want to put it live but the domain we use is already in use by the other devs application
Can you please remove the domain from the App? Thanks.

**Comment by marandino** [comment]
I'm sorry, can you give me more context about this? I don't really know what you meant there. 

The domain DNS' must be changed on [Google Domains](https://domains.google/).

**Comment by FloodThinkingUSD** [comment]
It says that insilicotrading.info is still in use by another app? If you could please remove the domain from your app that would be great. Thank you.

**Comment by marandino** [comment]
And as I said before, the DNS must be set manually on Google Domains pointing towards the "new" app... If your dev can't do that, then let me know the DNS target so I can do it myself.

I'll shut down the server, but as I said before, that'll not fix your issue.

**Comment by marandino** [comment]
Can you at least tell your guy to check the environment variables? all your e-mail is being sent to my personal account.
