### ISSUE TITLE
Password Reset Issue

### ISSUE THREAD

**Issue by FloodThinkingUSD** [marandino/insilico#8]
When trying to reset password the site breaks and gets sent to Application Error Page. Can this be fixed please! Thanks.

**Comment by marandino** [comment]
Thanks for the visibility on this issue, 

functionality-wise it's working properly, we're having some issue at rendering the page after reseting the password. Will update you back in like 10 minutes.

**Comment by FloodThinkingUSD** [comment]
Great just let me know once this is sorted, we are going to launch today I believe.

**Comment by FloodThinkingUSD** [comment]
Let me know when it's fixed

**Comment by marandino** [comment]
fixed
